"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Check, Crown, Sparkles, X, ArrowRight, ShieldCheck, CreditCard, AlertCircle, Loader2 } from "lucide-react";
import { PackType, PACK_CONFIGS, setUserPack, isUserAdmin } from "@/utils/subscriptionEngine";
import { createClient } from "@/lib/supabaseClient";

interface UpgradePackModalProps {
  isOpen: boolean;
  onClose: () => void;
  targetPack?: PackType;
}

export function UpgradePackModal({ isOpen, onClose, targetPack = "griffon" }: UpgradePackModalProps) {
  const router = useRouter();
  const [loadingProvider, setLoadingProvider] = useState<"fapshi" | "chariow" | "admin" | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [selectedPack, setSelectedPack] = useState<PackType>(targetPack);
  const adminMode = isUserAdmin();

  useEffect(() => {
    if (isOpen) {
      setErrorMsg(null);
      setLoadingProvider(null);
      if (targetPack) {
        setSelectedPack(targetPack);
      }
    }
  }, [isOpen, targetPack]);

  if (!isOpen) return null;

  // 1. Initialisation officielle du paiement Fapshi (Mode Candidat et Mode Test Réel Admin)
  const handleFapshiPayment = async () => {
    setLoadingProvider("fapshi");
    setErrorMsg(null);
    try {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();

      if (!user) {
        onClose();
        router.push(`/login?redirect=/dashboard/payments`);
        return;
      }

      // Appel à notre API serveur sécurisée qui impose les tarifs et contacte Fapshi
      const res = await fetch("/api/fapshi/initiate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          pack: selectedPack,
          // returnUrl is generated by the backend to include the reference
        })
      });

      const data = await res.json();

      if (!res.ok || !data.paymentUrl) {
        throw new Error(data.error || "Impossible d'initialiser le paiement avec Fapshi.");
      }

      // Redirection transparente et sécurisée vers la page de paiement hébergée Fapshi
      window.location.href = data.paymentUrl;

    } catch (e: any) {
      console.error("Erreur Fapshi Initiate:", e);
      setErrorMsg(e.message || "Erreur de communication avec la passerelle de paiement Fapshi.");
      setLoadingProvider(null);
    }
  };

  // 1b. Initialisation du paiement Chariow
  const handleChariowPayment = async () => {
    setLoadingProvider("chariow");
    setErrorMsg(null);
    try {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();

      if (!user) {
        onClose();
        router.push(`/login?redirect=/dashboard/payments`);
        return;
      }

      const res = await fetch("/api/chariow/initiate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          pack: selectedPack,
        })
      });

      const data = await res.json();

      if (!res.ok || !data.paymentUrl) {
        throw new Error(data.error || "Impossible d'initialiser le paiement Chariow : " + (data.error || ""));
      }

      window.location.href = data.paymentUrl;

    } catch (e: any) {
      console.error("Erreur Chariow Initiate:", e);
      setErrorMsg(e.message || "Erreur de communication avec la passerelle de paiement Chariow.");
      setLoadingProvider(null);
    }
  };

  // 2. Contournement Admin gratuit pour vos tests rapides de contenu
  const handleAdminFreeBypass = async () => {
    setLoadingProvider("admin");
    setErrorMsg(null);
    try {
      setUserPack(selectedPack);

      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const profRes = await supabase.from("profiles").select("is_admin").eq("id", user.id).single();
        if (profRes.data?.is_admin) {
          const { error } = await supabase.from("subscriptions").upsert({
            user_id: user.id,
            pack: selectedPack,
            plan: selectedPack,
            amount: "0",
            currency: "XAF",
            status: "active",
            started_at: new Date().toISOString(),
            expires_at: new Date(Date.now() + 30 * 24 * 3600 * 1000).toISOString(),
            updated_at: new Date().toISOString(),
          }, { onConflict: 'user_id' });
          
          await supabase.from("profiles").update({ subscription_type: selectedPack }).eq("id", user.id);
          
          if (!error) {
            window.dispatchEvent(new Event("storage_user_pack_updated"));
            window.location.reload();
            return;
          }
        }
        setErrorMsg("Seul un administrateur peut utiliser cette fonction gratuite.");
      }
    } catch (e: any) {
      setErrorMsg(e.message || "Erreur admin bypass.");
    } finally {
      setLoadingProvider(null);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white dark:bg-slate-950 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-2xl max-w-xl w-full p-5 sm:p-8 flex flex-col max-h-[92vh] sm:max-h-[90vh] animate-in fade-in zoom-in duration-200 relative my-auto">
        
        {/* Header & Badges (Fixe en haut) */}
        <div className="shrink-0 space-y-3 pb-3 border-b border-slate-100 dark:border-slate-800">
          {adminMode && (
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl p-3 flex items-center gap-2.5 text-amber-600 dark:text-amber-400 text-xs font-semibold">
              <Sparkles className="h-4 w-4 shrink-0 animate-pulse text-amber-500" />
              <span>
                <strong>Mode Admin :</strong> Test monétique réel Fapshi ou activation gratuite.
              </span>
            </div>
          )}

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 sm:h-11 sm:w-11 rounded-2xl bg-gradient-to-br from-amber-500 to-amber-600 text-slate-950 flex items-center justify-center font-bold shadow-md shadow-amber-500/20 shrink-0">
                <Crown className="h-5 w-5 sm:h-6 sm:w-6" />
              </div>
              <div>
                <h3 className="font-black text-base sm:text-lg text-slate-900 dark:text-white">Souscrire / Mettre à niveau</h3>
                <p className="text-[11px] sm:text-xs text-slate-500">Choisissez votre formule TCF Canada et réglez en toute sécurité.</p>
              </div>
            </div>

            <button onClick={onClose} disabled={loading} className="p-1 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 shrink-0 ml-2">
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Zone de contenu défilante sur mobile */}
        <div className="overflow-y-auto py-4 space-y-4 pr-1 flex-1">
          {errorMsg && (
            <div className="p-3.5 rounded-2xl bg-red-50 dark:bg-red-950/50 border border-red-200 dark:border-red-900/60 text-red-700 dark:text-red-300 text-xs font-bold flex items-center gap-2">
              <AlertCircle className="h-4 w-4 shrink-0 text-red-600" />
              <span>{errorMsg}</span>
            </div>
          )}

          {/* Packs Choice List */}
          <div className="space-y-3">
            {(["standard", "griffon", "vip"] as PackType[]).map((pKey) => {
              const p = PACK_CONFIGS[pKey];
              const isSelected = selectedPack === pKey;
              return (
                <div
                  key={pKey}
                  onClick={() => !loading && setSelectedPack(pKey)}
                  className={`p-3.5 sm:p-4 rounded-2xl border-2 transition-all cursor-pointer relative ${
                    isSelected
                      ? "border-amber-500 bg-amber-50/50 dark:bg-amber-950/30 shadow-sm"
                      : "border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700"
                  }`}
                >
                  {p.badge && (
                    <span className="absolute -top-3 right-4 bg-amber-600 text-white text-[9px] sm:text-[10px] font-black uppercase px-2.5 py-0.5 rounded-full shadow-sm">
                      {p.badge}
                    </span>
                  )}

                  <div className="flex justify-between items-start gap-2">
                    <div>
                      <h4 className="font-black text-sm text-slate-900 dark:text-white flex items-center gap-1.5">
                        {p.name}
                        {isSelected && <Check className="h-4 w-4 text-amber-600 dark:text-amber-400 stroke-[3]" />}
                      </h4>
                      <p className="text-[11px] sm:text-xs text-slate-500 mt-0.5 leading-snug">
                        {pKey === "standard" && "Validité 1 mois • 2 modules • 20 cours • 20 tests (durée standard)"}
                        {pKey === "griffon" && "Validité 1 mois • 10 modules • 500+ cours • Tests de 1h 30 • Corrections IA"}
                        {pKey === "vip" && "Validité 2 mois • 20 modules • 500+ cours • Tests de 2h 00 • Coaching 1-on-1"}
                      </p>
                    </div>
                    <span className="font-black text-sm sm:text-base text-amber-600 dark:text-amber-400 shrink-0">
                      {p.price}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Info box Fapshi */}
          <div className="bg-slate-50 dark:bg-slate-900/80 rounded-2xl p-3.5 border border-slate-200/60 dark:border-slate-800 flex items-center gap-3 text-[11px] sm:text-xs text-slate-600 dark:text-slate-400">
            <ShieldCheck className="h-5 w-5 sm:h-6 sm:w-6 text-emerald-600 shrink-0" />
            <p className="leading-relaxed">
              <strong className="font-bold text-slate-900 dark:text-white block">Paiement 100% sécurisé via Fapshi ou Chariow :</strong>
              Accepte MTN Mobile Money, Orange Money. Conservation de tous vos acquis.
            </p>
          </div>
        </div>

        {/* Action Buttons (Fixe en bas) */}
        <div className="shrink-0 pt-3 border-t border-slate-100 dark:border-slate-800/80">
          {adminMode ? (
            <div className="space-y-2">
              <button
                type="button"
                onClick={handleFapshiPayment}
                disabled={loading}
                className="w-full py-3 sm:py-3.5 rounded-2xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-black text-xs sm:text-sm shadow-lg shadow-blue-500/20 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {loading ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <>
                    <CreditCard className="h-4 w-4 shrink-0" />
                    <span className="truncate">Tester le paiement Fapshi (Mode Réel)</span>
                    <ArrowRight className="h-4 w-4 shrink-0" />
                  </>
                )}
              </button>

              <button
                type="button"
                onClick={handleAdminFreeBypass}
                disabled={loading}
                className="w-full py-2.5 sm:py-3 rounded-2xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-700 dark:text-amber-300 border border-amber-500/30 font-bold text-xs transition-all flex items-center justify-center gap-2 disabled:opacity-50"
              >
                <Sparkles className="h-3.5 w-3.5 shrink-0" />
                <span className="truncate">Confirmer gratuitement ({PACK_CONFIGS[selectedPack].name})</span>
              </button>
            </div>
          ) : (
            <div className="flex flex-col gap-2 sm:gap-3">
              <button
                type="button"
                onClick={handleFapshiPayment}
                disabled={loadingProvider !== null}
                className="w-full py-3 sm:py-3.5 rounded-2xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-slate-950 font-black text-xs sm:text-sm shadow-lg shadow-amber-500/20 transition-all flex items-center justify-center gap-1.5 sm:gap-2 disabled:opacity-50 overflow-hidden"
              >
                {loadingProvider === "fapshi" ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin text-slate-950 shrink-0" />
                    <span className="truncate">Redirection Fapshi...</span>
                  </>
                ) : (
                  <>
                    <CreditCard className="h-4 w-4 text-slate-950 shrink-0" />
                    <span className="truncate">S'abonner via Fapshi ({PACK_CONFIGS[selectedPack].price})</span>
                    <ArrowRight className="h-4 w-4 text-slate-950 shrink-0" />
                  </>
                )}
              </button>

              <button
                type="button"
                onClick={handleChariowPayment}
                disabled={loadingProvider !== null}
                className="w-full py-3 sm:py-3.5 rounded-2xl bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white font-black text-xs sm:text-sm shadow-lg shadow-blue-500/20 transition-all flex items-center justify-center gap-1.5 sm:gap-2 disabled:opacity-50 overflow-hidden"
              >
                {loadingProvider === "chariow" ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin text-white shrink-0" />
                    <span className="truncate">Redirection Chariow...</span>
                  </>
                ) : (
                  <>
                    <CreditCard className="h-4 w-4 text-white shrink-0" />
                    <span className="truncate">S'abonner via Chariow ({PACK_CONFIGS[selectedPack].price})</span>
                    <ArrowRight className="h-4 w-4 text-white shrink-0" />
                  </>
                )}
              </button>

              <button
                type="button"
                onClick={onClose}
                disabled={loadingProvider !== null}
                className="w-full mt-2 py-2 px-4 sm:px-5 rounded-2xl border border-slate-200 dark:border-slate-800 font-bold text-xs text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-900 shrink-0"
              >
                Annuler
              </button>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
